import { useAuth } from "@/_core/hooks/useAuth";
import { Button } from "@/components/ui/button";
import { EmptyWorkspace, PageHeading, StatusPill } from "@/components/WorkspaceUI";
import { trpc } from "@/lib/trpc";
import { ShieldAlert, ShieldCheck, UsersRound } from "lucide-react";
import { toast } from "sonner";

export default function AdminPage() { const { user } = useAuth(); const utils = trpc.useUtils(); const users = trpc.admin.users.useQuery(undefined, { enabled: user?.role === "admin" }); const updateRole = trpc.admin.updateRole.useMutation({ onSuccess: () => { users.refetch(); utils.activity.list.invalidate(); toast.success("Rol actualizado."); }, onError: error => toast.error(error.message) }); if (user?.role !== "admin") return <><PageHeading eyebrow="Acceso restringido" title="Administración" text="Esta área solo está disponible para personas con rol de administrador." /><section className="surface max-w-2xl p-8"><ShieldAlert className="text-destructive" /><h2 className="mt-4 text-xl font-bold">No tienes permiso para ver esta sección.</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">La protección también se aplica en el servidor: las operaciones administrativas no pueden ejecutarse sin el rol adecuado.</p></section></>; return <><PageHeading eyebrow="Gobierno del espacio" title="Administración" text="Gestiona los permisos de acceso de las personas usuarias de Nexo Ops." /><section className="surface overflow-hidden"><div className="flex items-center gap-3 border-b border-border/70 px-6 py-5"><span className="grid h-10 w-10 place-items-center rounded-xl bg-secondary text-primary"><UsersRound size={19} /></span><div><p className="font-bold">Usuarios y roles</p><p className="mt-1 text-xs text-muted-foreground">Los cambios de rol se aplican de inmediato y quedan registrados.</p></div></div>{users.isLoading ? <div className="h-80 animate-pulse" /> : <div className="divide-y divide-border/70">{users.data?.map(person => <div key={person.id} className="flex flex-wrap items-center gap-3 px-6 py-4"><span className="grid h-9 w-9 place-items-center rounded-full bg-muted text-xs font-bold text-muted-foreground">{person.name?.charAt(0).toUpperCase() || "U"}</span><div className="min-w-[190px] flex-1"><p className="text-sm font-bold">{person.name || "Sin nombre"}</p><p className="text-xs text-muted-foreground">{person.email || person.openId}</p></div><StatusPill value={person.role === "admin" ? "active" : "todo"} label={person.role === "admin" ? "Administrador" : "Usuario"} /><select aria-label={`Cambiar rol de ${person.name || "usuario"}`} className="h-9 rounded-lg border bg-background px-2 text-sm" value={person.role} disabled={person.id === user?.id || updateRole.isPending} onChange={event => updateRole.mutate({ userId: person.id, role: event.target.value as "admin" | "user" })}><option value="user">Usuario</option><option value="admin">Administrador</option></select></div>)}</div>}</section></>; }

