import { Button } from "@/components/ui/button";
import { EmptyWorkspace, dateLabel, PageHeading } from "@/components/WorkspaceUI";
import { trpc } from "@/lib/trpc";
import { Download, File, FileText, Loader2, Plus, Trash2, UploadCloud } from "lucide-react";
import { ChangeEvent, useEffect, useRef, useState } from "react";
import { toast } from "sonner";

function prettySize(size: number) { return size < 1024 * 1024 ? `${Math.max(1, Math.round(size / 1024))} KB` : `${(size / (1024 * 1024)).toFixed(1)} MB`; }
export default function FilesPage() {
  const utils = trpc.useUtils(); const projects = trpc.projects.list.useQuery(); const [projectId, setProjectId] = useState<number | null>(null); const input = useRef<HTMLInputElement>(null); useEffect(() => { if (!projectId && projects.data?.[0]) setProjectId(projects.data[0].id); }, [projectId, projects.data]); const files = trpc.files.list.useQuery({ projectId: projectId ?? 1 }, { enabled: Boolean(projectId) });
  const upload = trpc.files.upload.useMutation({ onSuccess: () => { files.refetch(); utils.activity.list.invalidate(); toast.success("Archivo subido."); }, onError: error => toast.error(error.message) }); const remove = trpc.files.remove.useMutation({ onSuccess: () => { files.refetch(); toast.success("Archivo eliminado de la lista."); }, onError: error => toast.error(error.message) }); const download = trpc.files.download.useMutation({ onSuccess: data => { window.location.assign(data.url); }, onError: error => toast.error(error.message) });
  const handleFile = (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file || !projectId) return; const reader = new FileReader(); reader.onload = () => upload.mutate({ projectId, originalName: file.name, mimeType: file.type || "application/octet-stream", contentBase64: String(reader.result) }); reader.onerror = () => toast.error("No se pudo leer el archivo seleccionado."); reader.readAsDataURL(file); event.target.value = ""; };
  return <><PageHeading eyebrow="Repositorio" title="Archivos" text="Conserva los materiales de cada proyecto en su contexto operativo." actions={<><select aria-label="Seleccionar proyecto" className="h-10 rounded-lg border bg-background px-3 text-sm" value={projectId ?? ""} onChange={event => setProjectId(Number(event.target.value))}><option value="">Selecciona un proyecto</option>{projects.data?.map(project => <option key={project.id} value={project.id}>{project.name}</option>)}</select><input ref={input} type="file" className="hidden" onChange={handleFile} /><Button disabled={!projectId || upload.isPending} onClick={() => input.current?.click()}>{upload.isPending ? <Loader2 className="animate-spin" size={16} /> : <UploadCloud size={16} />}{upload.isPending ? "Subiendo…" : "Subir archivo"}</Button></>} />
    {!projects.isLoading && !projects.data?.length ? <EmptyWorkspace title="No hay proyectos disponibles" text="Crea un proyecto antes de centralizar sus documentos y entregables." /> : files.isLoading ? <div className="space-y-3">{[1,2,3].map(key => <div key={key} className="surface h-18 animate-pulse" />)}</div> : files.data?.length ? <div className="surface divide-y divide-border/70">{files.data.map(file => <article className="flex items-center gap-4 px-5 py-4" key={file.id}><span className="grid h-10 w-10 place-items-center rounded-xl bg-secondary text-primary"><FileText size={18} /></span><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold">{file.originalName}</p><p className="mt-1 text-xs text-muted-foreground">{prettySize(file.sizeBytes)} · {dateLabel(file.createdAt)}</p></div><button onClick={() => download.mutate({ fileId: file.id })} disabled={download.isPending} className="rounded-lg p-2 text-muted-foreground hover:bg-muted hover:text-primary disabled:opacity-50" aria-label={`Descargar ${file.originalName}`}><Download size={16} /></button><button onClick={() => { if (window.confirm(`¿Retirar «${file.originalName}» de este proyecto?`)) remove.mutate({ fileId: file.id }); }} className="rounded-lg p-2 text-muted-foreground hover:bg-destructive/10 hover:text-destructive" aria-label={`Eliminar ${file.originalName}`}><Trash2 size={16} /></button></article>)}</div> : <EmptyWorkspace title="Este proyecto no tiene archivos" text="Sube una propuesta, entregable o documento para mantenerlo disponible al equipo." action={() => input.current?.click()} />}</>;
}
