import DashboardLayout from "@/components/DashboardLayout";
import { EmptyState, PageHeader, PriorityPill } from "@/components/ScannerUI";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";
import { BookOpenCheck, CheckCircle2, Download, ExternalLink, FileCheck2, LockKeyhole, Settings2, Waypoints } from "lucide-react";
import { useEffect, useState } from "react";
import { toast } from "sonner";
import { Link } from "wouter";

function downloadJson(filename: string, dossier: unknown) {
  const url = URL.createObjectURL(new Blob([JSON.stringify(dossier, null, 2)], { type: "application/json;charset=utf-8" }));
  const anchor = document.createElement("a"); anchor.href = url; anchor.download = filename; anchor.click(); URL.revokeObjectURL(url);
}

export default function Handoffs() {
  const utils = trpc.useUtils();
  const policy = trpc.handoffs.policy.useQuery();
  const connector = trpc.handoffs.connectorStatus.useQuery();
  const ready = trpc.prospects.list.useQuery({ readiness: "ready", limit: 200 });
  const queue = trpc.handoffs.list.useQuery();
  const [minimumScore, setMinimumScore] = useState(70);
  const [destination, setDestination] = useState("SaaS de auditoría web");
  const [requireNextAction, setRequireNextAction] = useState(true);
  const [requireDigitalEvidence, setRequireDigitalEvidence] = useState(true);
  useEffect(() => { if (policy.data) { setMinimumScore(policy.data.minimumOpportunityScore); setDestination(policy.data.destinationLabel); setRequireNextAction(Boolean(policy.data.requireNextAction)); setRequireDigitalEvidence(Boolean(policy.data.requireDigitalEvidence)); } }, [policy.data]);
  const updatePolicy = trpc.handoffs.updatePolicy.useMutation({ onSuccess: () => { utils.handoffs.policy.invalidate(); utils.prospects.list.invalidate(); toast.success("Criterios de transición actualizados."); }, onError: error => toast.error(error.message) });
  const queueProspect = trpc.handoffs.queue.useMutation({ onSuccess: () => { utils.handoffs.list.invalidate(); utils.prospects.list.invalidate(); toast.success("Oportunidad incorporada a la revisión de auditoría."); }, onError: error => toast.error(error.message) });
  const approve = trpc.handoffs.approve.useMutation({ onSuccess: () => { utils.handoffs.list.invalidate(); toast.success("Expediente autorizado para preparación."); }, onError: error => toast.error(error.message) });
  const dossier = trpc.handoffs.dossier.useMutation({ onSuccess: result => { downloadJson(result.filename, result.dossier); utils.handoffs.list.invalidate(); toast.success("Expediente JSON 2.0 preparado para revisión o entrega manual."); }, onError: error => toast.error(error.message) });
  const savePolicy = () => updatePolicy.mutate({ minimumOpportunityScore: minimumScore, destinationLabel: destination, requireNextAction, requireDigitalEvidence });
  const queuedIds = new Set((queue.data ?? []).map(item => item.prospect.id));

  return <DashboardLayout><PageHeader eyebrow="Fase 2 · Auditoría web" title="Transición a auditoría" description="Revisa oportunidades aptas, aprueba un expediente con alcance recomendado y entrégalo manualmente al SaaS que construirá o mejorará el sitio. Ningún dato sale de Nexo sin una acción explícita." actions={<Link href="/app/guia"><Button variant="outline"><BookOpenCheck size={16} />Guía de operación</Button></Link>} />
    <section className="mb-6 grid gap-4 rounded-3xl border border-violet-200 bg-gradient-to-r from-violet-50 via-white to-indigo-50 p-5 lg:grid-cols-[auto_1fr_auto] lg:items-center"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-primary text-primary-foreground"><FileCheck2 size={21} /></span><div><p className="text-xs font-bold uppercase tracking-[0.14em] text-primary">Expediente de auditoría 2.0</p><h2 className="mt-1 font-bold text-slate-950">Una base concreta para crear o mejorar un sitio web</h2><p className="mt-1 max-w-3xl text-sm leading-6 text-slate-600">Incluye la recomendación de servicio, señales de oportunidad, agenda de auditoría, alcance sugerido y checklist para el SaaS receptor. No crea propuestas ni sitios de forma automática.</p></div><Link href="/app/guia" className="text-sm font-bold text-primary hover:underline">Ver recorrido</Link></section>
    <div className="grid gap-5 xl:grid-cols-[1.12fr_.88fr]"><section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-3"><div><h2 className="font-bold">Criterios de aptitud</h2><p className="mt-1 text-sm text-slate-600">La regla combina score, seguimiento comercial y evidencia digital verificable.</p></div><Settings2 className="text-primary" size={20} /></div><div className="mt-5 grid gap-3 sm:grid-cols-2"><label className="text-sm font-semibold text-slate-700">Score mínimo<Input className="mt-1" type="number" min="0" max="100" value={minimumScore} onChange={event => setMinimumScore(Number(event.target.value))} /></label><label className="text-sm font-semibold text-slate-700">Destino previsto<Input className="mt-1" value={destination} onChange={event => setDestination(event.target.value)} /></label></div><div className="mt-4 grid gap-2 sm:grid-cols-2"><label className="flex cursor-pointer items-start gap-2 rounded-xl border border-slate-200 p-3 text-sm text-slate-700"><input type="checkbox" className="mt-1" checked={requireNextAction} onChange={event => setRequireNextAction(event.target.checked)} /><span><strong className="block">Exigir próxima acción</strong>La oportunidad necesita una acción comercial registrada.</span></label><label className="flex cursor-pointer items-start gap-2 rounded-xl border border-slate-200 p-3 text-sm text-slate-700"><input type="checkbox" className="mt-1" checked={requireDigitalEvidence} onChange={event => setRequireDigitalEvidence(event.target.checked)} /><span><strong className="block">Exigir evidencia digital</strong>Debe no tener sitio o contar con una evaluación web disponible.</span></label></div><Button className="mt-5" disabled={updatePolicy.isPending} onClick={savePolicy}>Guardar criterios</Button></section><section className="rounded-3xl border border-amber-200 bg-amber-50 p-5 shadow-sm"><div className="flex gap-3"><LockKeyhole className="mt-0.5 text-amber-700" size={20} /><div><h2 className="font-bold text-amber-950">Entrega externa protegida</h2><p className="mt-1 text-sm leading-6 text-amber-900">El conector al otro SaaS está {connector.data?.state === "activo" ? "activo" : "en modo placeholder inactivo"}. Mientras no se configure, exporta el expediente y entrégalo por tu canal autorizado.</p></div></div></section></div>
    <section className="mt-6 rounded-3xl border border-emerald-200 bg-emerald-50/50 p-5"><div className="flex items-center justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[0.14em] text-emerald-700">Aptas para revisar</p><h2 className="mt-1 text-xl font-bold">{ready.data?.length ?? 0} oportunidades cumplen los criterios</h2></div><Waypoints className="text-emerald-700" size={25} /></div><div className="mt-4 space-y-3">{ready.data?.length ? ready.data.map(item => <div key={item.prospect.id} className="flex flex-col gap-3 rounded-2xl border border-emerald-100 bg-white p-4 sm:flex-row sm:items-center sm:justify-between"><div><Link href={`/app/prospectos/${item.prospect.id}`}><strong className="hover:text-primary">{item.business.name}</strong></Link><p className="mt-1 text-sm text-slate-600">Score {item.prospect.opportunityScore}/100 · {item.business.websiteStatus === "no_website" ? "sin sitio" : "análisis web disponible"} · próxima acción: {item.prospect.nextActionLabel}</p></div>{queuedIds.has(item.prospect.id) ? <span className="inline-flex items-center gap-1 text-sm font-semibold text-emerald-700"><CheckCircle2 size={16} />En cola</span> : <Button size="sm" onClick={() => queueProspect.mutate({ prospectId: item.prospect.id })}>Preparar auditoría</Button>}</div>) : <p className="rounded-2xl bg-white p-4 text-sm text-slate-600">Aún no hay oportunidades aptas. Ajusta criterios o completa el seguimiento de los prospectos cualificados.</p>}</div></section>
    <section className="mt-6 rounded-3xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 px-5 py-4"><h2 className="font-bold">Cola de expedientes</h2></div>{queue.data?.length ? <div className="divide-y divide-slate-100">{queue.data.map(item => <div key={item.handoff.id} className="flex flex-col gap-3 px-5 py-4 lg:flex-row lg:items-center lg:justify-between"><div><div className="flex items-center gap-2"><Link href={`/app/prospectos/${item.prospect.id}`}><strong className="hover:text-primary">{item.business.name}</strong></Link><PriorityPill priority={item.prospect.priority} /></div><p className="mt-1 text-sm text-slate-600">{item.handoff.destinationLabel} · estado: <strong>{item.handoff.status.replaceAll("_", " ")}</strong></p></div><div className="flex flex-wrap gap-2">{item.handoff.status === "ready_for_review" && <Button size="sm" variant="outline" onClick={() => approve.mutate({ prospectId: item.prospect.id })}>Aprobar</Button>}{["approved", "package_exported"].includes(item.handoff.status) && <Button size="sm" onClick={() => dossier.mutate({ prospectId: item.prospect.id, markExported: true })}><Download size={15} />Expediente 2.0</Button>}<Link href={`/app/prospectos/${item.prospect.id}`} className="inline-flex items-center gap-1 rounded-md px-3 py-2 text-sm font-semibold text-primary hover:bg-primary/5"><ExternalLink size={15} />Ficha</Link></div></div>)}</div> : <EmptyState title="Aún no hay expedientes" description="Cuando apruebes una oportunidad apta, su expediente aparecerá aquí para revisión y entrega manual." href="/app/prospectos" action="Ver oportunidades" />}</section>
  </DashboardLayout>;
}
