import { useAuth } from "@/_core/hooks/useAuth";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { PageHeading } from "@/components/WorkspaceUI";
import { trpc } from "@/lib/trpc";
import { Save, UserRound } from "lucide-react";
import { FormEvent, useEffect, useState } from "react";
import { toast } from "sonner";

export default function ProfilePage() { const { user } = useAuth(); const [name, setName] = useState(""); const [avatarUrl, setAvatarUrl] = useState(""); const [themePreference, setThemePreference] = useState<"system" | "light" | "dark">("system"); const [timezone, setTimezone] = useState("UTC"); useEffect(() => { if (user) { setName(user.name ?? ""); setAvatarUrl(user.avatarUrl ?? ""); setThemePreference(user.themePreference ?? "system"); setTimezone(user.timezone ?? "UTC"); } }, [user]); const update = trpc.profile.update.useMutation({ onSuccess: () => toast.success("Preferencias guardadas."), onError: error => toast.error(error.message) }); const submit = (event: FormEvent) => { event.preventDefault(); update.mutate({ name: name || null, avatarUrl: avatarUrl || null, themePreference, timezone }); }; const initial = name?.split(" ").map(word => word[0]).join("").slice(0,2).toUpperCase() || "NX";
  return <><PageHeading eyebrow="Cuenta" title="Perfil y preferencias" text="Ajusta la identidad con la que apareces y la experiencia base de tu espacio." /><form onSubmit={submit} className="grid max-w-4xl gap-6 lg:grid-cols-[.75fr_1.25fr]"><section className="surface p-6"><Avatar className="h-20 w-20"><AvatarImage src={avatarUrl || undefined} /><AvatarFallback className="bg-secondary text-lg text-primary">{initial}</AvatarFallback></Avatar><h2 className="mt-5 font-bold">{name || "Tu perfil"}</h2><p className="mt-1 break-all text-sm text-muted-foreground">{user?.email || "Sesión protegida"}</p><div className="mt-5 rounded-xl bg-muted/60 p-3 text-xs leading-5 text-muted-foreground">Tu rol actual es <strong className="text-foreground">{user?.role === "admin" ? "Administrador" : "Usuario"}</strong>.</div></section><section className="surface p-6"><h2 className="text-lg font-bold tracking-tight">Información visible</h2><div className="mt-6 grid gap-5 sm:grid-cols-2"><label className="block text-sm font-medium">Nombre<Input className="mt-1.5" value={name} onChange={event => setName(event.target.value)} maxLength={120} /></label><label className="block text-sm font-medium">URL de avatar<Input className="mt-1.5" placeholder="https://…" type="url" value={avatarUrl} onChange={event => setAvatarUrl(event.target.value)} /></label><label className="block text-sm font-medium">Tema<select className="mt-1.5 h-10 w-full rounded-md border bg-background px-3 text-sm" value={themePreference} onChange={event => setThemePreference(event.target.value as typeof themePreference)}><option value="system">Sistema</option><option value="light">Claro</option><option value="dark">Oscuro</option></select></label><label className="block text-sm font-medium">Zona horaria<Input className="mt-1.5" value={timezone} onChange={event => setTimezone(event.target.value)} placeholder="Ej. Europe/Madrid" maxLength={64} /></label></div><div className="mt-7 flex justify-end"><Button type="submit" disabled={update.isPending}><Save size={16} />{update.isPending ? "Guardando…" : "Guardar preferencias"}</Button></div></section></form></>; }
