import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { EmptyWorkspace, dateLabel, PageHeading, projectStatusLabel, StatusPill } from "@/components/WorkspaceUI";
import { trpc } from "@/lib/trpc";
import { CalendarDays, FolderKanban, Pencil, Plus, Trash2, UserPlus, UsersRound } from "lucide-react";
import { FormEvent, useState } from "react";
import { toast } from "sonner";
import { useLocation } from "wouter";

type ProjectForm = { id?: number; name: string; description: string; status: "active" | "paused" | "completed"; dueDate: string };
const fresh: ProjectForm = { name: "", description: "", status: "active", dueDate: "" };
export default function ProjectsPage() {
  const [, setLocation] = useLocation(); const utils = trpc.useUtils(); const list = trpc.projects.list.useQuery(); const [open, setOpen] = useState(false); const [form, setForm] = useState<ProjectForm>(fresh); const [membersOpen, setMembersOpen] = useState(false); const [memberProject, setMemberProject] = useState<number | null>(null); const [userToAdd, setUserToAdd] = useState("");
  const create = trpc.projects.create.useMutation({ onSuccess: () => { utils.projects.list.invalidate(); setOpen(false); setForm(fresh); toast.success("Proyecto creado."); }, onError: error => toast.error(error.message) });
  const update = trpc.projects.update.useMutation({ onSuccess: () => { utils.projects.list.invalidate(); setOpen(false); setForm(fresh); toast.success("Proyecto actualizado."); }, onError: error => toast.error(error.message) });
  const remove = trpc.projects.remove.useMutation({ onSuccess: () => { utils.projects.list.invalidate(); toast.success("Proyecto eliminado."); }, onError: error => toast.error(error.message) });
  const members = trpc.projects.members.useQuery({ projectId: memberProject ?? 1 }, { enabled: Boolean(memberProject && membersOpen) });
  const availableUsers = trpc.projects.availableUsers.useQuery({ projectId: memberProject ?? 1 }, { enabled: Boolean(memberProject && membersOpen) });
  const addMember = trpc.projects.addMember.useMutation({ onSuccess: () => { members.refetch(); availableUsers.refetch(); utils.activity.list.invalidate(); setUserToAdd(""); toast.success("Miembro incorporado al proyecto."); }, onError: error => toast.error(error.message) });
  const submit = (event: FormEvent) => { event.preventDefault(); const payload = { name: form.name, description: form.description || null, status: form.status, dueDate: form.dueDate ? new Date(`${form.dueDate}T12:00:00`) : null }; form.id ? update.mutate({ projectId: form.id, ...payload }) : create.mutate(payload); };
  const editing = Boolean(form.id); const pending = create.isPending || update.isPending;
  return <><PageHeading eyebrow="Portafolio" title="Proyectos" text="Agrupa el trabajo estratégico y haz visible la dirección de cada iniciativa." actions={<Dialog open={open} onOpenChange={value => { setOpen(value); if (!value) setForm(fresh); }}><DialogTrigger asChild><Button onClick={() => setForm(fresh)}><Plus size={16} />Nuevo proyecto</Button></DialogTrigger><DialogContent><form onSubmit={submit}><DialogHeader><DialogTitle>{editing ? "Editar proyecto" : "Crear proyecto"}</DialogTitle><DialogDescription>Define el contexto inicial. Podrás ajustarlo en cualquier momento.</DialogDescription></DialogHeader><div className="space-y-4 py-5"><label className="block text-sm font-medium">Nombre<Input className="mt-1.5" value={form.name} onChange={event => setForm({ ...form, name: event.target.value })} required maxLength={160} /></label><label className="block text-sm font-medium">Descripción<Textarea className="mt-1.5 min-h-24" value={form.description} onChange={event => setForm({ ...form, description: event.target.value })} maxLength={5000} /></label><div className="grid gap-4 sm:grid-cols-2"><label className="block text-sm font-medium">Estado<select className="mt-1.5 h-10 w-full rounded-md border bg-background px-3 text-sm" value={form.status} onChange={event => setForm({ ...form, status: event.target.value as ProjectForm["status"] })}><option value="active">Activo</option><option value="paused">Pausado</option><option value="completed">Completado</option></select></label><label className="block text-sm font-medium">Fecha límite<Input className="mt-1.5" type="date" value={form.dueDate} onChange={event => setForm({ ...form, dueDate: event.target.value })} /></label></div></div><DialogFooter><Button type="button" variant="outline" onClick={() => setOpen(false)}>Cancelar</Button><Button type="submit" disabled={pending}>{pending ? "Guardando…" : editing ? "Guardar cambios" : "Crear proyecto"}</Button></DialogFooter></form></DialogContent></Dialog>} />
    <Dialog open={membersOpen} onOpenChange={value => { setMembersOpen(value); if (!value) { setMemberProject(null); setUserToAdd(""); } }}><DialogContent><DialogHeader><DialogTitle>Miembros del proyecto</DialogTitle><DialogDescription>Incorpora a personas que ya hayan accedido a Nexo Ops para asignarles tareas.</DialogDescription></DialogHeader><div className="space-y-4 py-4"><div className="flex gap-2"><select aria-label="Seleccionar persona para incorporar" className="h-10 min-w-0 flex-1 rounded-md border bg-background px-3 text-sm" value={userToAdd} onChange={event => setUserToAdd(event.target.value)}><option value="">Selecciona una persona</option>{availableUsers.data?.filter(person => !members.data?.some(member => member.userId === person.id)).map(person => <option key={person.id} value={person.id}>{person.name || person.email || `Usuario ${person.id}`}</option>)}</select><Button disabled={!userToAdd || addMember.isPending || !memberProject} onClick={() => memberProject && addMember.mutate({ projectId: memberProject, userId: Number(userToAdd) })}><UserPlus size={16} />Añadir</Button></div><div className="rounded-xl border border-border/70">{members.isLoading ? <p className="p-4 text-sm text-muted-foreground">Cargando miembros…</p> : members.data?.map(member => <div className="flex items-center gap-3 border-b border-border/70 px-4 py-3 last:border-0" key={member.userId}><span className="grid h-8 w-8 place-items-center rounded-full bg-secondary text-xs font-bold text-primary">{member.name?.charAt(0).toUpperCase() || "U"}</span><span className="min-w-0 flex-1"><strong className="block truncate text-sm">{member.name || "Sin nombre"}</strong><small className="block truncate text-xs text-muted-foreground">{member.email || "Sin correo"}</small></span><span className="font-mono text-[10px] uppercase tracking-wide text-muted-foreground">{member.role === "owner" ? "Propietario" : "Miembro"}</span></div>)}</div></div></DialogContent></Dialog>
    {list.isLoading ? <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{[1,2,3].map(key => <div className="surface h-52 animate-pulse" key={key} />)}</div> : list.data?.length ? <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{list.data.map(project => <article className="surface group flex min-h-56 flex-col p-6" key={project.id}><div className="flex items-start justify-between"><span className="grid h-10 w-10 place-items-center rounded-xl bg-secondary text-primary"><FolderKanban size={19} /></span><div className="flex items-center gap-1"><StatusPill value={project.status} label={projectStatusLabel[project.status]} /><button className="rounded-lg p-1.5 text-muted-foreground opacity-70 hover:bg-muted hover:text-foreground" onClick={() => { setForm({ id: project.id, name: project.name, description: project.description || "", status: project.status, dueDate: project.dueDate ? new Date(project.dueDate).toISOString().slice(0, 10) : "" }); setOpen(true); }} aria-label="Editar proyecto"><Pencil size={15} /></button></div></div><button className="mt-6 text-left" onClick={() => setLocation("/app/tareas?project=" + project.id)}><h2 className="truncate text-lg font-bold tracking-tight group-hover:text-primary">{project.name}</h2><p className="mt-2 line-clamp-2 text-sm leading-6 text-muted-foreground">{project.description || "Sin descripción todavía."}</p></button><div className="mt-auto flex items-center justify-between border-t border-border/70 pt-4 text-xs text-muted-foreground"><span className="flex items-center gap-1.5"><CalendarDays size={14} />{dateLabel(project.dueDate)}</span><div className="flex items-center gap-1"><button onClick={() => { setMemberProject(project.id); setMembersOpen(true); }} className="rounded-md p-1.5 text-muted-foreground hover:bg-muted hover:text-primary" aria-label="Gestionar miembros"><UsersRound size={15} /></button><button onClick={() => { if (window.confirm(`¿Eliminar «${project.name}»? Esta acción elimina también sus tareas y archivos.`)) remove.mutate({ projectId: project.id }); }} className="rounded-md p-1.5 text-muted-foreground hover:bg-destructive/10 hover:text-destructive" aria-label="Eliminar proyecto"><Trash2 size={15} /></button></div></div></article>)}</div> : <EmptyWorkspace title="El portafolio está vacío" text="Crea un proyecto para empezar a organizar iniciativas, tareas y archivos." action={() => { setForm(fresh); setOpen(true); }} />}</>;
}
