import DashboardLayout from "@/components/DashboardLayout";
import { PageHeader, PriorityPill } from "@/components/ScannerUI";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { ArrowLeft, CheckCircle2, ClipboardCopy, Download, ExternalLink, FileSpreadsheet, Gauge, Globe2, MapPin, Phone, Save, SendHorizontal, Star } from "lucide-react";
import { useEffect, useState } from "react";
import { toast } from "sonner";
import { Link, useRoute } from "wouter";

const labels: Record<string, string> = { websiteOpportunityScore: "Oportunidad web", businessAttractivenessScore: "Atractivo de negocio", digitalOpportunityScore: "Oportunidad digital", commercialPotentialScore: "Potencial comercial", leadPotentialScore: "Potencial de lead", urgencyScore: "Urgencia" };
const statuses = ["new", "qualified", "rejected", "exported", "analysis_pending", "analyzed", "demo_pending", "contact_pending", "contacted", "converted", "lost"] as const;
const statusLabels: Record<(typeof statuses)[number], string> = { new: "Nuevo", qualified: "Aprobado", rejected: "Descartado", exported: "Exportado", analysis_pending: "Auditoría pendiente", analyzed: "Analizado", demo_pending: "Demo pendiente", contact_pending: "Contacto pendiente", contacted: "Contactado", converted: "Convertido", lost: "Descartado" };

function downloadCsv(file: { filename: string; csv: string }) { const url = URL.createObjectURL(new Blob([file.csv], { type: "text/csv;charset=utf-8" })); const link = document.createElement("a"); link.href = url; link.download = file.filename; link.click(); URL.revokeObjectURL(url); }

export default function ProspectDetail() {
  const [, params] = useRoute("/app/prospectos/:id"); const id = Number(params?.id); const utils = trpc.useUtils();
  const item = trpc.prospects.get.useQuery({ prospectId: id }, { enabled: Boolean(id) }); const analyses = trpc.prospects.analyses.useQuery({ prospectId: id }, { enabled: Boolean(id) }); const exportsHistory = trpc.prospects.exports.useQuery({ prospectId: id }, { enabled: Boolean(id) }); const integrations = trpc.integrations.status.useQuery(); const templates = trpc.templates.list.useQuery();
  const [notes, setNotes] = useState(""); const [templateId, setTemplateId] = useState<number | null>(null);
  useEffect(() => { if (item.data) setNotes(item.data.prospect.notes || ""); }, [item.data]); useEffect(() => { if (!templateId && templates.data?.[0]) setTemplateId(templates.data[0].id); }, [templates.data, templateId]);
  const preview = trpc.templates.render.useQuery({ templateId: templateId ?? 1, prospectId: id }, { enabled: Boolean(id && templateId) });
  const update = trpc.prospects.update.useMutation({ onSuccess: () => { utils.prospects.get.invalidate({ prospectId: id }); utils.prospects.list.invalidate(); toast.success("Seguimiento actualizado."); }, onError: error => toast.error(error.message) });
  const analyze = trpc.prospects.analyzeWebsite.useMutation({ onSuccess: () => { analyses.refetch(); utils.prospects.get.invalidate({ prospectId: id }); utils.prospects.list.invalidate(); toast.success("Análisis web completado y puntuación actualizada."); }, onError: error => toast.error(error.message) });
  const exportSheet = trpc.prospects.exportGoogleSheets.useMutation({ onSuccess: data => { exportsHistory.refetch(); utils.prospects.get.invalidate({ prospectId: id }); toast.success(`${data.rowsWritten} fila(s) entregadas en ${data.destinationLabel}.`); }, onError: error => toast.error(error.message) });
  const exportCsv = trpc.prospects.exportCsv.useMutation({ onSuccess: data => { downloadCsv(data); toast.success("Archivo CSV descargado."); }, onError: error => toast.error(error.message) });
  if (item.isLoading) return <DashboardLayout><div className="h-72 animate-pulse rounded-3xl bg-slate-200" /></DashboardLayout>;
  if (!item.data) return <DashboardLayout><p className="text-sm text-slate-500">No se encontró esta oportunidad.</p></DashboardLayout>;
  const { prospect, business, run } = item.data; const scores = ["businessAttractivenessScore", "digitalOpportunityScore", "websiteOpportunityScore", "commercialPotentialScore", "leadPotentialScore", "urgencyScore"] as const; const latest = analyses.data?.[0]; const canExportToSheets = prospect.status === "qualified";
  return <DashboardLayout><Link href="/app/prospectos" className="mb-5 inline-flex items-center gap-2 text-sm font-bold text-slate-500 hover:text-primary"><ArrowLeft size={16} />Volver a oportunidades</Link><PageHeader eyebrow={`Ejecución ${run.publicId}`} title={business.name} description={`${business.category || "Categoría no disponible"} · ${business.address || [business.city, business.country].filter(Boolean).join(", ") || "Ubicación no disponible"}`} actions={<PriorityPill priority={prospect.priority} />} />
    <div className="mb-6 flex flex-wrap gap-2"><Button variant="outline" disabled={!business.website || analyze.isPending} onClick={() => analyze.mutate({ prospectId: id, strategy: "mobile" })} title={!business.website ? "Esta oportunidad no tiene un sitio web público que revisar." : "Analiza solo señales públicas del sitio; PageSpeed amplía métricas si se configura después."}><Gauge size={16} />{analyze.isPending ? "Analizando…" : "Analizar sitio público"}</Button><Button variant="outline" disabled={!integrations.data?.googleSheets.configured || !canExportToSheets || exportSheet.isPending} onClick={() => exportSheet.mutate({ prospectIds: [id] })} title={!integrations.data?.googleSheets.configured ? "Conector opcional: configura la cuenta de servicio, la hoja de destino y la activación expresa para habilitarlo." : !canExportToSheets ? "Solo las oportunidades con estado Aprobado se pueden enviar a Sheets." : undefined}><FileSpreadsheet size={16} />{exportSheet.isPending ? "Entregando…" : "Enviar a Sheets"}</Button><Button variant="outline" disabled={exportCsv.isPending} onClick={() => exportCsv.mutate({ prospectIds: [id] })}><Download size={16} />CSV</Button></div>
    <div className="grid gap-6 xl:grid-cols-[1.45fr_.85fr]"><div className="space-y-6"><section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[0.14em] text-primary">Opportunity Score</p><strong className="mt-2 block text-6xl tracking-[-0.06em]">{prospect.opportunityScore}<small className="text-xl text-slate-400">/100</small></strong></div><div className="max-w-md rounded-2xl bg-violet-50 p-4 text-sm leading-6 text-violet-950">{prospect.analysisSummary}</div></div><div className="mt-7 grid gap-3 sm:grid-cols-2">{prospect.scoreReasons?.length ? prospect.scoreReasons.map((reason: { label: string; points: number }, index: number) => <div key={`${reason.label}-${index}`} className="flex items-center justify-between rounded-xl bg-slate-50 px-4 py-3"><span className="text-sm text-slate-600">{reason.label}</span><strong className={reason.points > 0 ? "text-emerald-700" : "text-rose-700"}>{reason.points > 0 ? "+" : ""}{reason.points}</strong></div>) : <p className="text-sm text-slate-500">No hay razones de puntuación disponibles.</p>}</div></section>
      <section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center justify-between"><div><h2 className="text-lg font-bold">Análisis web público</h2><p className="mt-1 text-sm text-slate-500">Revisa únicamente señales públicas del sitio. PageSpeed, si se configura, añade métricas detalladas.</p></div>{business.websiteQuality && <span className="rounded-full bg-violet-100 px-3 py-1 text-xs font-black uppercase tracking-wide text-primary">{business.websiteQuality.replace("_", " ")}</span>}</div>{latest?.status === "completed" ? <div className="mt-5"><div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{[["Rendimiento", latest.performanceScore], ["Accesibilidad", latest.accessibilityScore], ["Prácticas", latest.bestPracticesScore], ["SEO", latest.seoScore]].map(([label, score]) => <div className="rounded-2xl bg-slate-50 p-4" key={String(label)}><p className="text-xs font-bold text-slate-500">{label}</p><strong className="mt-2 block text-2xl">{score ?? "—"}<small className="text-sm text-slate-400">/100</small></strong></div>)}</div><p className="mt-4 text-sm leading-6 text-slate-600">{latest.summary}</p></div> : <div className="mt-5 rounded-2xl bg-slate-50 p-4 text-sm leading-6 text-slate-500">{business.website ? "Aún no hay un análisis guardado. Ejecuta la revisión pública para incorporar señales verificables al puntaje." : "La fuente no proporcionó un sitio web público que analizar."}</div>}</section>
      <section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-lg font-bold">Datos disponibles</h2><div className="mt-5 grid gap-4 sm:grid-cols-2"><div className="rounded-2xl bg-slate-50 p-4"><MapPin size={17} className="text-primary" /><strong className="mt-3 block text-sm">Ubicación</strong><p className="mt-1 text-sm leading-6 text-slate-500">{business.address || "No encontrada"}</p></div><div className="rounded-2xl bg-slate-50 p-4"><Phone size={17} className="text-primary" /><strong className="mt-3 block text-sm">Teléfono</strong><p className="mt-1 text-sm leading-6 text-slate-500">{business.phone || "No encontrado"}</p></div><div className="rounded-2xl bg-slate-50 p-4"><Globe2 size={17} className="text-primary" /><strong className="mt-3 block text-sm">Sitio web</strong><p className="mt-1 break-all text-sm leading-6 text-slate-500">{business.website || "No encontrado"}</p>{business.website && <a href={business.website} target="_blank" rel="noreferrer" className="mt-3 inline-flex items-center gap-1 text-xs font-bold text-primary">Abrir sitio <ExternalLink size={13} /></a>}</div><div className="rounded-2xl bg-slate-50 p-4"><Star size={17} className="text-primary" /><strong className="mt-3 block text-sm">Ficha pública</strong><p className="mt-1 text-sm leading-6 text-slate-500">{business.rating ?? "No disponible"} · {business.reviewCount ?? 0} reseñas</p>{business.googleMapsUrl && <a href={business.googleMapsUrl} target="_blank" rel="noreferrer" className="mt-3 inline-flex items-center gap-1 text-xs font-bold text-primary">Abrir fuente <ExternalLink size={13} /></a>}</div></div></section></div>
      <aside className="space-y-6"><section className="rounded-3xl bg-slate-950 p-6 text-white"><p className="text-xs font-bold uppercase tracking-[0.14em] text-violet-300">Subpuntuaciones</p><div className="mt-5 space-y-4">{scores.map(score => <div key={score}><div className="flex items-center justify-between text-sm"><span className="text-slate-300">{labels[score]}</span><strong>{prospect[score]}</strong></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-violet-400" style={{ width: `${prospect[score]}%` }} /></div></div>)}</div><div className="mt-7 border-t border-white/10 pt-5"><p className="text-xs text-slate-400">Tipos de oportunidad</p><div className="mt-2 flex flex-wrap gap-2">{prospect.opportunityTypes?.length ? prospect.opportunityTypes.map((type: string) => <span key={type} className="rounded-full bg-white/10 px-2.5 py-1 text-[10px] font-bold tracking-wide">{type}</span>) : <span className="text-sm text-slate-400">Sin clasificación</span>}</div></div></section>
        <section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="font-bold">Borrador de cualificación</h2><p className="mt-2 text-sm leading-6 text-slate-500">Solo genera una vista previa. No se envía ningún mensaje desde Nexo.</p><select className="mt-4 h-10 w-full rounded-md border border-input bg-background px-3 text-sm" value={templateId ?? ""} onChange={event => setTemplateId(Number(event.target.value))}>{templates.data?.map(template => <option key={template.id} value={template.id}>{template.name}</option>)}</select>{preview.data && <><pre className="mt-4 max-h-52 overflow-auto whitespace-pre-wrap rounded-2xl bg-slate-950 p-4 font-sans text-xs leading-5 text-slate-200">{preview.data.subject ? `${preview.data.subject}\n\n` : ""}{preview.data.body}</pre><Button className="mt-3 w-full" variant="outline" onClick={() => navigator.clipboard.writeText(`${preview.data.subject ? `${preview.data.subject}\n\n` : ""}${preview.data.body}`).then(() => toast.success("Borrador copiado al portapapeles."))}><ClipboardCopy size={16} />Copiar borrador</Button></>}</section>
        <section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="font-bold">Seguimiento interno</h2><p className="mt-2 text-sm leading-6 text-slate-500">Estas notas no modifican los datos de la fuente ni de aplicaciones posteriores.</p><Textarea className="mt-4 min-h-28" value={notes} onChange={event => setNotes(event.target.value)} placeholder="Añade contexto para tu próxima revisión…" /><div className="mt-4 flex gap-2"><select className="h-10 min-w-0 flex-1 rounded-md border border-input bg-background px-2 text-sm" value={prospect.status} onChange={event => update.mutate({ prospectId: id, status: event.target.value as typeof statuses[number] })}>{statuses.map(status => <option key={status} value={status}>{statusLabels[status]}</option>)}</select><Button disabled={update.isPending} onClick={() => update.mutate({ prospectId: id, notes })}><Save size={16} />Guardar</Button></div></section>
        {exportsHistory.data?.length ? <section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="font-bold">Entregas registradas</h2><div className="mt-4 space-y-3">{exportsHistory.data.map(entry => <div className="flex items-center gap-3 rounded-xl bg-slate-50 p-3 text-sm" key={entry.id}><CheckCircle2 size={16} className={entry.status === "succeeded" ? "text-emerald-600" : "text-rose-600"} /><span className="min-w-0 flex-1 truncate">{entry.destinationLabel}</span><small className="text-slate-500">{entry.status === "succeeded" ? "Entregado" : "Falló"}</small></div>)}</div></section> : null}</aside></div></DashboardLayout>;
}
