import DashboardLayout from "@/components/DashboardLayout";
import { EmptyState, PageHeader, localDate } from "@/components/ScannerUI";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { ArrowUpRight, Compass, Database, ListChecks, ShieldAlert } from "lucide-react";
import { Link } from "wouter";

const state: Record<string, string> = { queued: "En cola", running: "En curso", paused: "Pausada", completed: "Completada", partial: "Parcial", failed: "Con errores", cancelled: "Cancelada" };
export default function RunsHistory() { const runs = trpc.runs.list.useQuery({ limit: 100 }); return <DashboardLayout><PageHeader eyebrow="Trazabilidad" title="Historial de prospecciones" description="Cada búsqueda conserva su plan, estado, resultados, eventos y errores recuperables para que puedas revisar o continuar el trabajo con contexto." actions={<Link href="/app/nueva-prospeccion"><Button><Compass size={16} />Nueva prospección</Button></Link>} /><div className="rounded-3xl border border-slate-200 bg-white shadow-sm">{runs.data?.length ? <div className="divide-y divide-slate-100">{runs.data.map(run => <Link key={run.id} href={`/app/historial/${run.id}`} className="flex flex-col gap-4 p-5 transition-colors hover:bg-violet-50/40 md:flex-row md:items-center"><span className="grid h-11 w-11 place-items-center rounded-xl bg-slate-100 text-primary"><Database size={18} /></span><span className="min-w-0 flex-1"><strong className="block truncate text-sm">{run.primaryCategory} · {run.district || run.city}, {run.country}</strong><small className="mt-1 block text-xs text-slate-500">{run.publicId} · {localDate(run.createdAt)} · radio {run.radiusMeters.toLocaleString("es-ES")} m</small></span><span className="grid grid-cols-3 gap-5 text-right"><small><strong className="block text-base text-slate-900">{run.foundCount}</strong><span className="text-[10px] uppercase tracking-wide text-slate-400">Encontrados</span></small><small><strong className="block text-base text-slate-900">{run.uniqueCount}</strong><span className="text-[10px] uppercase tracking-wide text-slate-400">Únicos</span></small><small><strong className="block text-base text-slate-900">{run.qualifiedCount}</strong><span className="text-[10px] uppercase tracking-wide text-slate-400">Aprobados</span></small></span><span className={run.status === "completed" ? "rounded-full bg-emerald-100 px-3 py-1 text-xs font-bold text-emerald-700" : run.status === "partial" ? "rounded-full bg-amber-100 px-3 py-1 text-xs font-bold text-amber-700" : run.status === "failed" ? "rounded-full bg-rose-100 px-3 py-1 text-xs font-bold text-rose-700" : "rounded-full bg-slate-100 px-3 py-1 text-xs font-bold text-slate-700"}>{state[run.status] || run.status}</span><ArrowUpRight size={17} className="text-slate-400" /></Link>)}</div> : runs.isLoading ? <div className="h-80 animate-pulse bg-slate-100" /> : <EmptyState title="El historial está vacío" description="Tus ejecuciones quedarán disponibles aquí junto con el plan y los eventos del proveedor." href="/app/nueva-prospeccion" action="Crear una prospección" />}</div></DashboardLayout>; }
