import { useAuth } from "@/_core/hooks/useAuth";
import DashboardLayout from "@/components/DashboardLayout";
import { PageHeader } from "@/components/ScannerUI";
import { ScoringCalibrationPanel } from "@/components/ScoringCalibrationPanel";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";
import { CheckCircle2, CircleOff, FileSpreadsheet, KeyRound, Save, ShieldCheck, SlidersHorizontal } from "lucide-react";
import { FormEvent, useEffect, useState } from "react";
import { toast } from "sonner";

type Limits = { dailyRequestBudget: number; monthlyRequestBudget: number; maxCostPerRunCents: number; maxBusinessesPerRun: number; maxAiCallsPerRun: number };

export default function Settings() {
  const { user } = useAuth(); const budget = trpc.settings.budget.useQuery(); const profiles = trpc.settings.scoringProfiles.useQuery(); const integrations = trpc.integrations.status.useQuery(); const utils = trpc.useUtils();
  const [values, setValues] = useState<Limits>({ dailyRequestBudget: 100, monthlyRequestBudget: 2000, maxCostPerRunCents: 0, maxBusinessesPerRun: 20, maxAiCallsPerRun: 0 }); const [weights, setWeights] = useState("");
  useEffect(() => { if (budget.data) setValues({ dailyRequestBudget: budget.data.dailyRequestBudget, monthlyRequestBudget: budget.data.monthlyRequestBudget, maxCostPerRunCents: budget.data.maxCostPerRunCents, maxBusinessesPerRun: budget.data.maxBusinessesPerRun, maxAiCallsPerRun: budget.data.maxAiCallsPerRun }); }, [budget.data]); useEffect(() => { if (profiles.data?.[0]) setWeights(JSON.stringify(profiles.data[0].weights, null, 2)); }, [profiles.data]);
  const updateBudget = trpc.settings.updateBudget.useMutation({ onSuccess: () => { utils.settings.budget.invalidate(); toast.success("Límites actualizados."); }, onError: error => toast.error(error.message) }); const updateScore = trpc.settings.updateScoring.useMutation({ onSuccess: () => { utils.settings.scoringProfiles.invalidate(); toast.success("Ponderaciones actualizadas."); }, onError: error => toast.error(error.message) }); const updateProfile = trpc.profile.update.useMutation({ onSuccess: () => toast.success("Perfil actualizado."), onError: error => toast.error(error.message) });
  const saveBudget = (event: FormEvent) => { event.preventDefault(); updateBudget.mutate(values); }; const saveWeights = () => { const profile = profiles.data?.[0]; if (!profile) return; try { const parsed = JSON.parse(weights); if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) throw new Error(); updateScore.mutate({ profileId: profile.id, weights: parsed as Record<string, number> }); } catch { toast.error("Usa un objeto JSON con claves y valores numéricos."); } };
  const fields: Array<[string, keyof Limits]> = [["Límite diario de solicitudes", "dailyRequestBudget"], ["Límite mensual de solicitudes", "monthlyRequestBudget"], ["Coste máximo por ejecución (céntimos)", "maxCostPerRunCents"], ["Máximo de negocios por ejecución", "maxBusinessesPerRun"], ["Máximo de llamadas IA por ejecución", "maxAiCallsPerRun"]];
  const providerDetail: Record<string, { title: string; detail: string }> = { googleMaps: { title: "Google Places (opcional)", detail: "Fuente oficial disponible solo tras una activación expresa del operador." }, googleSheets: { title: "Google Sheets (opcional)", detail: "Entrega auditable solo tras configurar una cuenta de servicio." }, websiteAnalyzer: { title: "PageSpeed Insights (opcional)", detail: "Aporta métricas Lighthouse; el análisis público básico no depende de este conector." } };
  return <DashboardLayout><PageHeader eyebrow="Controles del sistema" title="Configuración y fuentes" description="Importación manual y CSV funcionan por defecto. Los conectores externos son mejoras opcionales configurables sin editar código." /><div className="grid gap-6 xl:grid-cols-2"><form onSubmit={saveBudget} className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-violet-100 text-violet-700"><ShieldCheck size={18} /></span><div><h2 className="font-bold">Límites de consumo</h2><p className="mt-1 text-sm text-slate-500">La previsualización bloquea cualquier plan que los supere.</p></div></div><div className="mt-6 grid gap-4 sm:grid-cols-2">{fields.map(([label, key]) => <label key={key} className="text-sm font-semibold">{label}<Input className="mt-2" type="number" min="0" value={values[key]} onChange={event => setValues({ ...values, [key]: Number(event.target.value) })} /></label>)}</div><Button className="mt-6" type="submit" disabled={updateBudget.isPending}><Save size={16} />Guardar límites</Button></form>
    <section className="rounded-3xl border border-emerald-200 bg-emerald-50/40 p-6 shadow-sm"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-emerald-100 text-emerald-700"><FileSpreadsheet size={18} /></span><div><h2 className="font-bold">Fuentes sin coste</h2><p className="mt-1 text-sm text-slate-600">CSV y entrada manual están listos sin credenciales, sin scraping y sin llamadas a proveedores externos.</p></div></div><p className="mt-5 text-sm leading-6 text-slate-600">Cada importación conserva su procedencia, se normaliza, se deduplica y se puntúa con las mismas reglas que las campañas conectadas.</p></section>
    <section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-emerald-100 text-emerald-700"><KeyRound size={18} /></span><div><h2 className="font-bold">Estado de proveedores</h2><p className="mt-1 text-sm text-slate-500">Las credenciales se guardan como secretos del proyecto y nunca viajan al navegador.</p></div></div><div className="mt-6 space-y-3">{Object.entries(integrations.data || {}).map(([name, config]) => <div className="flex items-center justify-between gap-4 rounded-2xl bg-slate-50 px-4 py-3" key={name}><span><strong className="block text-sm">{providerDetail[name]?.title || name}</strong><small className="text-xs text-slate-500">{providerDetail[name]?.detail} {!config.configured && ` ${config.activation}`}</small></span><span className={config.configured ? "flex shrink-0 items-center gap-1 text-xs font-bold text-emerald-700" : "flex shrink-0 items-center gap-1 text-xs font-bold text-amber-700"}>{config.configured ? <><CheckCircle2 size={14} />Activo</> : <><CircleOff size={14} />Inactivo — placeholder</>}</span></div>)}</div><p className="mt-5 rounded-2xl bg-amber-50 p-4 text-xs leading-5 text-amber-900">El modo sin coste bloquea cualquier llamada a estos conectores hasta que el operador configure las credenciales necesarias y establezca <code>NEXO_ENABLE_PAID_CONNECTORS=true</code>. Consulta <code>CONFIGURACION.md</code> para los permisos mínimos, variables y límites.</p></section>
    <section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-amber-100 text-amber-700"><SlidersHorizontal size={18} /></span><div><h2 className="font-bold">Puntuación explicable</h2><p className="mt-1 text-sm text-slate-500">Los pesos se almacenan por perfil y se aplican solo sobre señales verificadas.</p></div></div><textarea className="mt-5 min-h-60 w-full rounded-xl border border-input bg-slate-950 p-4 font-mono text-xs leading-6 text-emerald-200 outline-none focus:ring-2 focus:ring-primary" value={weights} onChange={event => setWeights(event.target.value)} aria-label="Pesos de puntuación" /><Button className="mt-4" disabled={updateScore.isPending || !profiles.data?.length} onClick={saveWeights}><Save size={16} />Guardar pesos</Button></section>
    <ScoringCalibrationPanel disabled={!profiles.data?.length || updateScore.isPending} onApply={nextWeights => { const profile = profiles.data?.[0]; if (!profile) return; setWeights(JSON.stringify(nextWeights, null, 2)); updateScore.mutate({ profileId: profile.id, weights: nextWeights }); }} />
    <form onSubmit={event => { event.preventDefault(); const fd = new FormData(event.currentTarget); updateProfile.mutate({ name: String(fd.get("name") || "").trim() || null, timezone: String(fd.get("timezone") || "UTC") }); }} className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="font-bold">Perfil del operador</h2><p className="mt-1 text-sm text-slate-500">Preferencias básicas de la cuenta actual.</p><label className="mt-5 block text-sm font-semibold">Nombre<Input name="name" className="mt-2" defaultValue={user?.name || ""} /></label><label className="mt-4 block text-sm font-semibold">Zona horaria<Input name="timezone" className="mt-2" defaultValue={Intl.DateTimeFormat().resolvedOptions().timeZone || "UTC"} /></label><Button type="submit" className="mt-5" disabled={updateProfile.isPending}>Guardar perfil</Button></form></div></DashboardLayout>;
}
