import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { EmptyWorkspace, PageHeading, priorityLabel, StatusPill, taskStatusLabel } from "@/components/WorkspaceUI";
import { trpc } from "@/lib/trpc";
import { Check, Circle, Pencil, Plus, Search, Trash2 } from "lucide-react";
import { FormEvent, useEffect, useState } from "react";
import { toast } from "sonner";
import { useLocation } from "wouter";

type TaskForm = { id?: number; title: string; description: string; assigneeId: string; priority: "low" | "medium" | "high" | "urgent"; status: "todo" | "in_progress" | "done"; dueDate: string };
const fresh: TaskForm = { title: "", description: "", assigneeId: "", priority: "medium", status: "todo", dueDate: "" };
export default function TasksPage() {
  const [location] = useLocation(); const params = new URLSearchParams(location.split("?")[1]); const requested = Number(params.get("project")); const utils = trpc.useUtils(); const projects = trpc.projects.list.useQuery(); const [projectId, setProjectId] = useState<number | null>(Number.isInteger(requested) && requested > 0 ? requested : null); const [status, setStatus] = useState<"" | "todo" | "in_progress" | "done">(""); const [priority, setPriority] = useState<"" | "low" | "medium" | "high" | "urgent">(""); const [query, setQuery] = useState(""); const [open, setOpen] = useState(false); const [form, setForm] = useState<TaskForm>(fresh);
  useEffect(() => { if (!projectId && projects.data?.[0]) setProjectId(projects.data[0].id); }, [projectId, projects.data]);
  const tasks = trpc.tasks.list.useQuery({ projectId: projectId ?? 1, status: status || undefined, priority: priority || undefined, query: query || undefined }, { enabled: Boolean(projectId) });
  const members = trpc.projects.members.useQuery({ projectId: projectId ?? 1 }, { enabled: Boolean(projectId) });
  const create = trpc.tasks.create.useMutation({ onSuccess: () => { tasks.refetch(); utils.dashboard.metrics.invalidate(); setOpen(false); setForm(fresh); toast.success("Tarea creada."); }, onError: error => toast.error(error.message) });
  const update = trpc.tasks.update.useMutation({ onSuccess: () => { tasks.refetch(); utils.dashboard.metrics.invalidate(); toast.success("Tarea actualizada."); }, onError: error => toast.error(error.message) });
  const remove = trpc.tasks.remove.useMutation({ onSuccess: () => { tasks.refetch(); utils.dashboard.metrics.invalidate(); toast.success("Tarea eliminada."); }, onError: error => toast.error(error.message) });
  const submit = (event: FormEvent) => { event.preventDefault(); if (!projectId) return; const payload = { title: form.title, description: form.description || null, assigneeId: form.assigneeId ? Number(form.assigneeId) : null, priority: form.priority, status: form.status, dueDate: form.dueDate ? new Date(`${form.dueDate}T12:00:00`) : null }; if (form.id) update.mutate({ taskId: form.id, ...payload }); else create.mutate({ projectId, ...payload }); };
  const editing = Boolean(form.id); const isSaving = create.isPending || update.isPending;
  return <><PageHeading eyebrow="Ejecución" title="Tareas" text="Convierte los proyectos en el próximo paso correcto, sin perder el contexto." actions={<Dialog open={open} onOpenChange={value => { setOpen(value); if (!value) setForm(fresh); }}><DialogTrigger asChild><Button disabled={!projectId} onClick={() => setForm(fresh)}><Plus size={16} />Nueva tarea</Button></DialogTrigger><DialogContent><form onSubmit={submit}><DialogHeader><DialogTitle>{editing ? "Editar tarea" : "Crear tarea"}</DialogTitle></DialogHeader><div className="space-y-4 py-5"><label className="block text-sm font-medium">Título<Input className="mt-1.5" value={form.title} onChange={event => setForm({ ...form, title: event.target.value })} required maxLength={200} /></label><label className="block text-sm font-medium">Descripción<Textarea className="mt-1.5 min-h-20" value={form.description} onChange={event => setForm({ ...form, description: event.target.value })} /></label><div className="grid gap-3 sm:grid-cols-2"><label className="block text-sm font-medium">Responsable<select className="mt-1.5 h-10 w-full rounded-md border bg-background px-2 text-sm" value={form.assigneeId} onChange={event => setForm({ ...form, assigneeId: event.target.value })}><option value="">Sin asignar</option>{members.data?.map(member => <option key={member.userId} value={member.userId}>{member.name || member.email || "Usuario"}{member.role === "owner" ? " (propietario)" : ""}</option>)}</select></label><label className="block text-sm font-medium">Límite<Input className="mt-1.5" type="date" value={form.dueDate} onChange={event => setForm({ ...form, dueDate: event.target.value })} /></label></div><div className="grid gap-3 sm:grid-cols-2"><label className="block text-sm font-medium">Prioridad<select className="mt-1.5 h-10 w-full rounded-md border bg-background px-2 text-sm" value={form.priority} onChange={event => setForm({ ...form, priority: event.target.value as TaskForm["priority"] })}><option value="low">Baja</option><option value="medium">Media</option><option value="high">Alta</option><option value="urgent">Urgente</option></select></label><label className="block text-sm font-medium">Estado<select className="mt-1.5 h-10 w-full rounded-md border bg-background px-2 text-sm" value={form.status} onChange={event => setForm({ ...form, status: event.target.value as TaskForm["status"] })}><option value="todo">Pendiente</option><option value="in_progress">En curso</option><option value="done">Completada</option></select></label></div></div><DialogFooter><Button type="button" variant="outline" onClick={() => setOpen(false)}>Cancelar</Button><Button type="submit" disabled={isSaving}>{isSaving ? "Guardando…" : editing ? "Guardar cambios" : "Crear tarea"}</Button></DialogFooter></form></DialogContent></Dialog>} />
    <div className="surface mb-5 grid gap-3 p-4 lg:grid-cols-[minmax(190px,.8fr)_1fr_auto_auto]"><select aria-label="Seleccionar proyecto" className="h-10 rounded-lg border bg-background px-3 text-sm" value={projectId ?? ""} onChange={event => setProjectId(Number(event.target.value))}><option value="">Selecciona un proyecto</option>{projects.data?.map(project => <option key={project.id} value={project.id}>{project.name}</option>)}</select><label className="relative"><Search size={16} className="absolute left-3 top-3 text-muted-foreground" /><Input className="pl-9" placeholder="Buscar tarea…" value={query} onChange={event => setQuery(event.target.value)} /></label><select aria-label="Filtrar por estado" className="h-10 rounded-lg border bg-background px-3 text-sm" value={status} onChange={event => setStatus(event.target.value as typeof status)}><option value="">Todos los estados</option><option value="todo">Pendientes</option><option value="in_progress">En curso</option><option value="done">Completadas</option></select><select aria-label="Filtrar por prioridad" className="h-10 rounded-lg border bg-background px-3 text-sm" value={priority} onChange={event => setPriority(event.target.value as typeof priority)}><option value="">Todas las prioridades</option><option value="low">Baja</option><option value="medium">Media</option><option value="high">Alta</option><option value="urgent">Urgente</option></select></div>
    {!projects.isLoading && !projects.data?.length ? <EmptyWorkspace title="Primero crea un proyecto" text="Las tareas se organizan dentro de un proyecto para que cada prioridad tenga contexto." /> : tasks.isLoading ? <div className="space-y-3">{[1,2,3].map(key => <div className="surface h-20 animate-pulse" key={key} />)}</div> : tasks.data?.length ? <div className="space-y-3">{tasks.data.map(task => <article key={task.id} className="surface flex items-center gap-4 p-4"><button onClick={() => update.mutate({ taskId: task.id, status: task.status === "done" ? "todo" : "done" })} className={`grid h-9 w-9 shrink-0 place-items-center rounded-xl border transition-colors ${task.status === "done" ? "border-emerald-500 bg-emerald-500 text-white" : "border-border text-muted-foreground hover:border-primary hover:text-primary"}`} aria-label={task.status === "done" ? "Marcar como pendiente" : "Completar tarea"}>{task.status === "done" ? <Check size={17} /> : <Circle size={15} />}</button><div className="min-w-0 flex-1"><p className={`truncate text-sm font-bold ${task.status === "done" ? "text-muted-foreground line-through" : ""}`}>{task.title}</p><p className="mt-1 truncate text-xs text-muted-foreground">{task.description || "Sin descripción"}</p></div><div className="hidden gap-2 lg:flex"><StatusPill value={task.priority} label={priorityLabel[task.priority]} /><StatusPill value={task.status} label={taskStatusLabel[task.status]} /></div><button className="rounded-lg p-2 text-muted-foreground hover:bg-muted hover:text-primary" onClick={() => { setForm({ id: task.id, title: task.title, description: task.description || "", assigneeId: task.assigneeId ? String(task.assigneeId) : "", priority: task.priority, status: task.status, dueDate: task.dueDate ? new Date(task.dueDate).toISOString().slice(0, 10) : "" }); setOpen(true); }} aria-label="Editar tarea"><Pencil size={16} /></button><button className="rounded-lg p-2 text-muted-foreground hover:bg-destructive/10 hover:text-destructive" onClick={() => { if (window.confirm(`¿Eliminar la tarea «${task.title}»?`)) remove.mutate({ taskId: task.id }); }} aria-label="Eliminar tarea"><Trash2 size={16} /></button></article>)}</div> : <EmptyWorkspace title="No hay tareas con estos filtros" text="Ajusta la búsqueda o crea una nueva tarea para este proyecto." action={() => setOpen(true)} />}</>;
}
