import DashboardLayout from "@/components/DashboardLayout";
import { PageHeader } from "@/components/ScannerUI";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { Copy, FileCheck2, Mail, Pencil, Plus, Trash2 } from "lucide-react";
import { FormEvent, useEffect, useState } from "react";
import { toast } from "sonner";

type TemplateForm = { id?: number; name: string; type: "qualification" | "contact"; subject: string; body: string };
const blank: TemplateForm = { name: "", type: "qualification", subject: "", body: "" };

export default function Templates() {
  const utils = trpc.useUtils();
  const templates = trpc.templates.list.useQuery();
  const [form, setForm] = useState<TemplateForm>(blank);
  const [editing, setEditing] = useState(false);
  const create = trpc.templates.create.useMutation({ onSuccess: () => { utils.templates.list.invalidate(); close(); toast.success("Plantilla creada."); }, onError: error => toast.error(error.message) });
  const update = trpc.templates.update.useMutation({ onSuccess: () => { utils.templates.list.invalidate(); close(); toast.success("Plantilla actualizada."); }, onError: error => toast.error(error.message) });
  const remove = trpc.templates.remove.useMutation({ onSuccess: () => { utils.templates.list.invalidate(); toast.success("Plantilla eliminada."); }, onError: error => toast.error(error.message) });
  const close = () => { setForm(blank); setEditing(false); };
  const submit = (event: FormEvent) => { event.preventDefault(); if (form.id) update.mutate({ templateId: form.id, name: form.name, subject: form.type === "contact" ? form.subject || null : null, body: form.body }); else create.mutate({ name: form.name, type: form.type, subject: form.type === "contact" ? form.subject || null : null, body: form.body }); };
  return <DashboardLayout><PageHeader eyebrow="Mensajería asistida" title="Plantillas de cualificación" description="Estandariza las notas y borradores de contacto. Nexo no envía mensajes ni contacta a ningún negocio automáticamente." actions={<Button onClick={() => { close(); setEditing(true); }}><Plus size={16} />Nueva plantilla</Button>} />
    <div className="grid gap-6 xl:grid-cols-[1.15fr_.85fr]">{editing && <section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="mb-5 flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-violet-100 text-primary">{form.type === "contact" ? <Mail size={18} /> : <FileCheck2 size={18} />}</span><div><h2 className="font-bold">{form.id ? "Editar plantilla" : "Nueva plantilla"}</h2><p className="text-sm text-slate-500">Puedes usar: <code>{"{{business_name}}"}</code>, <code>{"{{location}}"}</code>, <code>{"{{opportunity_score}}"}</code>, <code>{"{{opportunity_reasons}}"}</code>.</p></div></div><form className="space-y-4" onSubmit={submit}><label className="block text-sm font-bold">Nombre<Input className="mt-1.5" value={form.name} onChange={event => setForm({ ...form, name: event.target.value })} required maxLength={120} /></label><label className="block text-sm font-bold">Tipo<select className="mt-1.5 h-10 w-full rounded-md border border-input bg-background px-3 text-sm" value={form.type} onChange={event => setForm({ ...form, type: event.target.value as TemplateForm["type"] })} disabled={Boolean(form.id)}><option value="qualification">Cualificación interna</option><option value="contact">Borrador de contacto</option></select></label>{form.type === "contact" && <label className="block text-sm font-bold">Asunto<Input className="mt-1.5" value={form.subject} onChange={event => setForm({ ...form, subject: event.target.value })} maxLength={180} /></label>}<label className="block text-sm font-bold">Contenido<Textarea className="mt-1.5 min-h-64 font-mono text-sm" value={form.body} onChange={event => setForm({ ...form, body: event.target.value })} required maxLength={10000} /></label><div className="flex gap-3"><Button type="submit" disabled={create.isPending || update.isPending}>{form.id ? "Guardar cambios" : "Crear plantilla"}</Button><Button type="button" variant="outline" onClick={close}>Cancelar</Button></div></form></section>}
      <section className={`space-y-4 ${editing ? "" : "xl:col-span-2"}`}>{templates.isLoading ? <div className="h-48 animate-pulse rounded-3xl bg-slate-200" /> : templates.data?.map(template => <article className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm" key={template.id}><div className="flex items-start justify-between gap-4"><div className="flex items-center gap-3"><span className={`grid h-10 w-10 place-items-center rounded-xl ${template.type === "contact" ? "bg-violet-100 text-primary" : "bg-emerald-100 text-emerald-700"}`}>{template.type === "contact" ? <Mail size={18} /> : <FileCheck2 size={18} />}</span><div><h2 className="font-bold">{template.name}</h2><p className="mt-0.5 text-xs font-bold uppercase tracking-wide text-slate-400">{template.type === "contact" ? "Borrador de contacto" : "Cualificación interna"}</p></div></div><div className="flex gap-1"><button className="rounded-lg p-2 text-slate-500 hover:bg-slate-100 hover:text-primary" onClick={() => { setForm({ id: template.id, name: template.name, type: template.type, subject: template.subject || "", body: template.body }); setEditing(true); }} aria-label="Editar plantilla"><Pencil size={16} /></button><button className="rounded-lg p-2 text-slate-500 hover:bg-rose-50 hover:text-rose-600" onClick={() => { if (window.confirm(`¿Eliminar la plantilla «${template.name}»?`)) remove.mutate({ templateId: template.id }); }} aria-label="Eliminar plantilla"><Trash2 size={16} /></button></div></div>{template.subject && <p className="mt-5 rounded-xl bg-slate-50 px-4 py-3 text-sm font-bold">Asunto: {template.subject}</p>}<pre className="mt-4 whitespace-pre-wrap rounded-2xl bg-slate-950 p-4 font-sans text-sm leading-6 text-slate-200">{template.body}</pre></article>)}</section></div></DashboardLayout>;
}
