export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  googleServiceAccountJson: process.env.NEXO_GOOGLE_SERVICE_ACCOUNT_JSON ?? "",
  googleSheetsSpreadsheetId: process.env.NEXO_GOOGLE_SHEETS_SPREADSHEET_ID ?? "",
  googleSheetsTab: process.env.NEXO_GOOGLE_SHEETS_TAB ?? "Prospectos",
  googlePageSpeedApiKey: process.env.NEXO_GOOGLE_PAGESPEED_API_KEY ?? "",
  paidConnectorsEnabled: process.env.NEXO_ENABLE_PAID_CONNECTORS === "true",
  handoffConnectorEnabled: process.env.NEXO_ENABLE_HANDOFF_CONNECTOR === "true",
  handoffWebhookUrl: process.env.NEXO_HANDOFF_WEBHOOK_URL ?? "",
};
