import { cn } from "@/lib/utils";
import { ArrowUpRight, DatabaseZap } from "lucide-react";
import type { ReactNode } from "react";
import { Link } from "wouter";

export const priorityStyle: Record<string, string> = { p0: "bg-violet-100 text-violet-800", p1: "bg-rose-100 text-rose-800", p2: "bg-amber-100 text-amber-800", p3: "bg-slate-100 text-slate-700", ignore: "bg-slate-100 text-slate-500" };
export const priorityLabel: Record<string, string> = { p0: "P0 · Excepcional", p1: "P1 · Alta prioridad", p2: "P2 · Oportunidad media", p3: "P3 · Baja prioridad", ignore: "Ignorar" };

export function PageHeader({ eyebrow, title, description, actions }: { eyebrow: string; title: string; description: string; actions?: ReactNode }) { return <section className="mb-8 flex flex-col gap-5 md:flex-row md:items-end md:justify-between"><div><p className="mb-2 text-xs font-bold uppercase tracking-[0.16em] text-primary">{eyebrow}</p><h1 className="text-3xl font-bold tracking-[-0.04em] text-slate-950 sm:text-4xl">{title}</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-500">{description}</p></div>{actions && <div className="flex shrink-0 items-center gap-3">{actions}</div>}</section>; }
export function MetricCard({ label, value, note, tone = "slate" }: { label: string; value: string | number; note: string; tone?: "slate" | "violet" | "amber" | "emerald" }) { const tones = { slate: "from-slate-900 to-slate-700", violet: "from-violet-700 to-violet-500", amber: "from-amber-500 to-orange-400", emerald: "from-emerald-700 to-emerald-500" }; return <article className={cn("relative overflow-hidden rounded-2xl bg-gradient-to-br p-5 text-white shadow-lg", tones[tone])}><p className="text-xs font-bold uppercase tracking-[0.14em] text-white/70">{label}</p><strong className="mt-5 block text-4xl tracking-[-0.05em]">{value}</strong><p className="mt-3 text-xs leading-5 text-white/75">{note}</p><DatabaseZap className="absolute -bottom-3 -right-3 h-20 w-20 text-white/10" /></article>; }
export function PriorityPill({ priority }: { priority: string }) { return <span className={cn("inline-flex rounded-full px-2.5 py-1 text-[11px] font-bold", priorityStyle[priority] ?? priorityStyle.ignore)}>{priorityLabel[priority] ?? priority}</span>; }
export function EmptyState({ title, description, href, action }: { title: string; description: string; href?: string; action?: string }) { return <div className="rounded-3xl border border-dashed border-slate-300 bg-white px-6 py-16 text-center"><span className="mx-auto grid h-11 w-11 place-items-center rounded-xl bg-slate-100 text-primary"><DatabaseZap size={19} /></span><h2 className="mt-4 text-lg font-bold">{title}</h2><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-slate-500">{description}</p>{href && <Link href={href} className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-primary">{action || "Continuar"}<ArrowUpRight size={15} /></Link>}</div>; }
export const localDate = (value: Date | string | null | undefined) => value ? new Date(value).toLocaleDateString("es-ES", { day: "2-digit", month: "short", year: "numeric" }) : "No disponible";
